### ISSUE TITLE
原神

### ISSUE THREAD

**Issue by bufvhj** [Official-Ayrton990/android_kernel_xiaomi_sm8250#1]
原神图标变大
![Screenshot_2021-09-15-22-56-28-722_com miHoYo Yuanshen](https://user-images.githubusercontent.com/90782663/133473859-2c710866-fc06-48d6-85cc-2a523a8188c0.jpg)

**Comment by bufvhj** [comment]
![Screenshot_2021-09-15-22-56-28-722_com miHoYo Yuanshen](https://user-images.githubusercontent.com/90782663/133491189-6a6ba642-c14a-4faa-909a-3ef3903ec0ed.jpg)

**Comment by wacharayo** [comment]
> 原神图标变大
> ![Screenshot_2021-09-15-22-56-28-722_com miHoYo Yuanshen](https://user-images.githubusercontent.com/90782663/133473859-2c710866-fc06-48d6-85cc-2a523a8188c0.jpg)

**Comment by Official-Ayrton990** [comment]
Please report in English next time, that's why issue closed. Then the bug has been addressed and will be fixed next update.
