### ISSUE TITLE
Abnormal wake-up 

### ISSUE THREAD

**Issue by lateautumn233** [Official-Ayrton990/android_kernel_xiaomi_sm8250#3]
![Screenshot_2021-10-27-10-09-28-377_com miui securitycenter](https://user-images.githubusercontent.com/63851402/138988007-a94bcc12-f83a-41cf-aa67-535f666bc6a7.jpg)

I tried to modify your source code to use on MIUI. 
android.system.suspend@1.0-service Wake-up abnormality 

Source Code:  https://github.com/lateautumn233/android_kernel_xiaomi_sm8250/tree/990rebase

log: https://netcut.cn/api/file/download/?note_id=6dca1c800471f797&file_id=20211027_cn008b09mw79k7fdd9iny66lgne2bt6a

Thanks.

**Comment by Official-Ayrton990** [comment]
[    2.481692] init: Parsing file /system/etc/init/android.system.suspend@1.0-service.rc...

Parsing that service will grant system to acquire BLOCK_SUSPEND capabilities. My kernel hard blocked userspace capabilities to block suspend, so the service is probably splitting error codes about not being able to block suspend. You can send me logcat to confirm this. This should be caused from MIUI framework, also can cause random reboots. Fixing should be possible by reverting the commits blocking suspend capabilities. Or other option is to make the node dummy after reverting to, it will not tamper to userspace requests. 

This doesn't happen on AOSP btw.

**Comment by lateautumn233** [comment]
> [ 2.481692] init: Parsing file /system/etc/init/android.system.suspend@1.0-service.rc...
> 
> Parsing that service will grant system to acquire BLOCK_SUSPEND capabilities. My kernel hard blocked userspace capabilities to block suspend, so the service is probably splitting error codes about not being able to block suspend. You can send me logcat to confirm this. This should be caused from MIUI framework, also can cause random reboots. Fixing should be possible by reverting the commits blocking suspend capabilities. Or other option is to make the node dummy after reverting to, it will not tamper to userspace requests.
> 
> This doesn't happen on AOSP btw.

Which is the specific submission ?
Thanks
